# Generated by Django 5.2.3 on 2025-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(choices=[('Simple', 'Simple'), ('Medium', 'Medium'), ('Complex', 'Complex')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('num_languages', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LiveVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('Newsdesk', 'Newsdesk'), ('Course Video', 'Course Video'), ('Bespoke Video', 'Bespoke Video'), ('Music Video', 'Music Video')], max_length=50)),
                ('num_seconds', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
