# Generated by Django 5.2.3 on 2025-06-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('Explainer 1', 'Explainer 1'), ('Explainer 2', 'Explainer 2'), ('Explainer 3', 'Explainer 3')], max_length=50)),
                ('num_seconds', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
