# Generated by Django 5.2.3 on 2025-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_animatedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(choices=[('Kennington', 'Kennington'), ('SLV Studio 1', 'SLV Studio 1'), ('SLV Studio 2', 'SLV Studio 2')], max_length=50)),
                ('filming_days', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
