# Generated by Django 5.2.3 on 2025-06-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sarah', 'Sarah'), ('Sam', 'Sam'), ('Matt', 'Matt'), ('Nicolette', 'Nicolette'), ('Drew', 'Drew'), ('Warrick', 'Warrick'), ('Neil', 'Neil')], max_length=50)),
                ('role_type', models.CharField(blank=True, choices=[('Live Actor', 'Live Actor'), ('Puppeteer', 'Puppeteer')], max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('live_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='quotes.livevideo')),
            ],
        ),
    ]
