# Generated by Django 5.2.3 on 2025-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_talent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filming_days', models.PositiveIntegerField(default=1)),
                ('editing_days', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
