# Generated by Django 5.2.3 on 2025-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_technicalstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(choices=[('Simple', 'Simple'), ('Medium', 'Medium'), ('Complex', 'Complex')], max_length=20)),
                ('role_name', models.CharField(max_length=100)),
                ('fixed_hours', models.FloatField()),
                ('hourly_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudioRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=100)),
                ('hire_rate', models.FloatField()),
                ('studio_staff', models.FloatField()),
                ('equipment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoTypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Live', 'Live'), ('Animated', 'Animated')], max_length=20)),
                ('type_name', models.CharField(max_length=100)),
                ('rate_per_second', models.FloatField()),
            ],
        ),
    ]
