# Generated by Django 5.2.3 on 2025-06-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_courseresource_fixedcost_studiorate_videotyperate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('Live Actor', 'Live Actor'), ('Puppeteer', 'Puppeteer')], max_length=20)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('daily_rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='role_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
